export default {
  CUSTOMER_ID: 'id',
  FULL_NAME: 'full_name',
  BIRTHDAY: 'date_of_birth',
  GENDER: 'gender',
  EMAIL: 'email',
  PHONE_NUMBER: 'phone_number',
  ADDRESS: 'address',
  CITY: 'city',
  COUNTRY: 'country',
  EMPLOYMENT_STATUS: 'employment_status',
  ACCOUNT_ID: 'account_id',
  ACCOUNT_TYPE: 'account_type',
  ACCOUNT_BALANCE: 'account_balance',
  CURRENCY: 'currency',
  ACCOUNT_OPEN_DATE: 'account_open_date',
  ACCOUNT_STATUS: 'account_status',
  TRANSACTION_ID: 'transaction_id',
  TRANSACTION_DATE: 'transaction_date',
  TRANSACTION_TYPE: 'transaction_type',
  TRANSACTION_AMOUNT: 'transaction_amount',
  TRANSACTION_CURRENCY: 'currency',
  BALANCE_AFTER_TRANSACTION: 'balance_after_transaction',
  TRANSACTION_METHOD: 'transaction_method',
  TRANSACTION_LOCATION: 'transaction_location',
}
