export default {
  CONSUMERS_STATE: 'CONSUMERS_STATE',
  HAS_CONSUMERS_STATE: 'HAS_CONSUMERS_STATE',
  LOAD_CONSUMERS_ACTION: 'LOAD_CONSUMERS_ACTION',
  SET_CONSUMERS_MUTATION: 'SET_CONSUMERS_MUTATION',
}
