export default {
  CONSUMERS_STATE: 'CONSUMERS_STATE',
  HAS_CONSUMERS_STATE: 'HAS_CONSUMERS_STATE',
  TRANSACTION_TYPE_DISTRIBUTION_STATE: 'TRANSACTION_TYPE_DISTRIBUTION_STATE',
  TRANSACTION_LOCATION_STATE: 'TRANSACTION_LOCATION_STATE',
  CONSUMERS_GENDER_STATE: 'CONSUMERS_GENDER_STATE',
  LOAD_CONSUMERS_ACTION: 'LOAD_CONSUMERS_ACTION',
  UPDATE_CONSUMER_INFO_ACTION: 'UPDATE_CONSUMER_INFO_ACTION',
  DELETE_CONSUMER_ACTION: 'DELETE_CONSUMER_ACTION',
  SET_CONSUMERS_MUTATION: 'SET_CONSUMERS_MUTATION',
  UPDATE_CONSUMER_MUTATION: 'UPDATE_CONSUMER_MUTATION',
  DELETE_CONSUMER_MUTATION: 'DELETE_CONSUMER_MUTATION',
}
